version: '3'

services:
  venice-autobooker:
    container_name: venicebeach
    build: .
    restart: unless-stopped
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - venicebeach_data:/app/data
    environment:
      - DB_PATH=/app/data/fitness.db
      - TZ=Europe/Berlin
    networks:
      homelab_public:
        ipv4_address: 10.20.30.15


networks:
  homelab_public:
    external: true

volumes:
  venicebeach_data:

